# Generated by Django 5.1.4 on 2025-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
