# Generated by Django 5.1.4 on 2025-02-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team_members/')),
            ],
        ),
    ]
